
import 'package:ecommerce_app/infrastructure/database/core/obay_database.dart';
import 'package:injectable/injectable.dart';
import 'package:moor_flutter/moor_flutter.dart';

part 'users_table.g.dart';


class OUsers extends Table{
  // User id is generated by the firebase auth. hence there is no need to generate one using AUTO INCREMENT
  TextColumn get userID => text().customConstraint('NOT NULL UNIQUE')();
  TextColumn get fullName => text().withLength(max: 100)();
  TextColumn get email => text().customConstraint('NOT NULL UNIQUE')();
  TextColumn get password => text().customConstraint('NOT NULL')();
  TextColumn get gender => text().nullable()();
  TextColumn get phoneNo => text().nullable()();
  BlobColumn get profilePic => blob().nullable()();

  //Set userID as primary Key
  @override
  Set<Column> get primaryKey => {userID};
}
// User Table Data Access Object
@LazySingleton()
@UseDao(tables: [OUsers])
class OUserDAO extends DatabaseAccessor<ObayDatabase> with _$OUserDAOMixin{
  final ObayDatabase db;
  // Called by the OBayDatabase class
  OUserDAO(this.db) : super(db);

  Future<OUser> getUserByID(String uID){
    return (select(oUsers)..where((t) => t.userID.equals(uID))).getSingle();
  }
  Future insertUser(OUsersCompanion oUser) {

    return into(oUsers).insert(oUser);
  }
  Future updateUser(OUsersCompanion oUser) => update(oUsers).replace(oUser);
  // Future deleteUser(OUsersCompanion oUser) => delete(oUsers).delete(oUser);
}
